
CREATE TABLE "Adobe_images" (
   id_local NUMBER ,
   id_global NUMBER ,
   aspectRatioCache NUMBER ,
   bitDepth NUMBER ,
   captureTime NUMBER ,
   colorChannels NUMBER ,
   colorLabels NUMBER ,
   colorMode NUMBER ,
   copyCreationTime NUMBER ,
   copyName NUMBER ,
   copyReason NUMBER ,
   developSettingsIDCache NUMBER ,
   editLock NUMBER ,
   fileFormat NUMBER ,
   fileHeight NUMBER ,
   fileWidth NUMBER ,
   hasMissingSidecars NUMBER ,
   masterImage NUMBER ,
   orientation NUMBER ,
   originalCaptureTime NUMBER ,
   originalRootEntity NUMBER ,
   panningDistanceH NUMBER ,
   panningDistanceV NUMBER ,
   pick NUMBER ,
   positionInFolder NUMBER ,
   propertiesCache NUMBER ,
   pyramidIDCache NUMBER ,
   rating NUMBER ,
   rootFile NUMBER ,
   sidecarStatus NUMBER ,
   touchCount NUMBER ,
   touchTime NUMBER ,
   CONSTRAINT Adobe_images_PK PRIMARY KEY (id_local)
)

/*
CREATE TABLE Adobe_images (
    id_local INTEGER PRIMARY KEY,
    id_global UNIQUE NOT NULL,
    aspectRatioCache NOT NULL DEFAULT -1,
    bitDepth NOT NULL DEFAULT 0,
    captureTime,
    colorChannels NOT NULL DEFAULT 0,
    colorLabels NOT NULL DEFAULT '',
    colorMode NOT NULL DEFAULT -1,
    copyCreationTime NOT NULL DEFAULT -63113817600,
    copyName,
    copyReason,
    developSettingsIDCache,
    editLock INTEGER NOT NULL DEFAULT 0,
    fileFormat NOT NULL DEFAULT 'unset',
    fileHeight,
    fileWidth,
    hasMissingSidecars INTEGER,
    masterImage INTEGER,
    orientation,
    originalCaptureTime,
    originalRootEntity INTEGER,
    panningDistanceH,
    panningDistanceV,
    pick NOT NULL DEFAULT 0,
    positionInFolder NOT NULL DEFAULT 'z',
    propertiesCache,
    pyramidIDCache,
    rating,
    rootFile INTEGER NOT NULL DEFAULT 0,
    sidecarStatus,
    touchCount NOT NULL DEFAULT 0,
    touchTime NOT NULL DEFAULT 0
)
*/
