
CREATE TABLE "Adobe_imageDevelopSettings" (
   id_local NUMBER ,
   allowFastRender NUMBER ,
   beforeSettingsIDCache VARCHAR2(32000) ,
   croppedHeight VARCHAR2(32000) ,
   croppedWidth VARCHAR2(32000) ,
   digest VARCHAR2(32000) ,
   fileHeight VARCHAR2(32000) ,
   fileWidth VARCHAR2(32000) ,
   filterHeight VARCHAR2(32000) ,
   filterWidth VARCHAR2(32000) ,
   grayscale NUMBER ,
   hasAIMasks NUMBER ,
   hasBigData NUMBER ,
   hasDevelopAdjustments NUMBER ,
   hasDevelopAdjustmentsEx VARCHAR2(32000) ,
   hasLensBlur NUMBER ,
   hasMasks NUMBER ,
   hasPointColor NUMBER ,
   hasRetouch VARCHAR2(32000) ,
   hasSettings1 VARCHAR2(32000) ,
   hasSettings2 VARCHAR2(32000) ,
   historySettingsID VARCHAR2(32000) ,
   image NUMBER ,
   isHdrEditMode NUMBER ,
   processVersion VARCHAR2(32000) ,
   profileCorrections VARCHAR2(32000) ,
   removeChromaticAberration VARCHAR2(32000) ,
   settingsID VARCHAR2(32000) ,
   snapshotID VARCHAR2(32000) ,
   text VARCHAR2(32000) ,
   validatedForVersion VARCHAR2(32000) ,
   whiteBalance VARCHAR2(32000) ,
   CONSTRAINT Adobe_imageDevelopSettings_PK PRIMARY KEY (id_local)
)

/*
CREATE TABLE Adobe_imageDevelopSettings (
    id_local INTEGER PRIMARY KEY,
    allowFastRender INTEGER,
    beforeSettingsIDCache,
    croppedHeight,
    croppedWidth,
    digest,
    fileHeight,
    fileWidth,
    filterHeight,
    filterWidth,
    grayscale INTEGER,
    hasAIMasks INTEGER NOT NULL DEFAULT 0,
    hasBigData INTEGER NOT NULL DEFAULT 0,
    hasDevelopAdjustments INTEGER,
    hasDevelopAdjustmentsEx,
    hasLensBlur INTEGER NOT NULL DEFAULT 0,
    hasMasks INTEGER NOT NULL DEFAULT 0,
    hasPointColor INTEGER NOT NULL DEFAULT 0,
    hasRetouch,
    hasSettings1,
    hasSettings2,
    historySettingsID,
    image INTEGER,
    isHdrEditMode INTEGER NOT NULL DEFAULT 0,
    processVersion,
    profileCorrections,
    removeChromaticAberration,
    settingsID,
    snapshotID,
    text,
    validatedForVersion,
    whiteBalance
)
*/
